{
 "title": "TEST_USER_MANAGEMENT",
 "description": "Robot Framework Test Results Grafana Dashboard in PostgreSQL for TESTING_OVERPASS",
 "time": { "from": "2023-03-06T09:10:52.722Z", "to": "2023-03-06T12:35:32.470Z" },
 "panels": [
  {
   "title": "Automation Execution Status - Last Test",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  failed AS \"Failed\",\n  passed AS \"Passed\"\nFROM automation_execution_results\nWHERE suite_name='TC User Registration'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(suite_name)\nFROM automation_execution_results\nWHERE suite_name='TC User Registration';"
    }
   ]
  },
  {
   "title": "Avg Success Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  sum(passed)/(sum(passed)+sum(failed)) as \"success_rate\"\nFROM\n  automation_execution_results\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg Failure Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  sum(failed)/(sum(passed)+sum(failed)) as \"success_rate\"\nFROM\n  automation_execution_results\n  WHERE suite_name='TC User Registration'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg Execution Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  (avg(suite_execution_time)/(1000)) as \"suite_execution_time\"\nFROM\n  automation_execution_results\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Executions - Time Period",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(start_time), suite_name,\n  passed, failed, CAST(suite_execution_time AS FLOAT)/1000 as execution_time\nFROM\n  automation_execution_results\nWHERE suite_name='TC User Registration'\n"
    }
   ]
  },
  {
   "title": "Top 5 Failed Tests Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  test_case.id, test_case.name, (count(test_result.status)/2) as failed_count\nFROM\n  suite \ninner join suite_result on suite_result.suite_id = suite.id\ninner join test_run on suite_result.test_run_id = test_run.id\ninner join test_result on suite_result.test_run_id = test_result.test_run_id\ninner join test_case on test_result.test_id = test_case.id\nWHERE\n  test_result.status = 'FAIL'::text \ngroup by test_case.id order by failed_count desc;"
    }
   ]
  },
  {
   "title": "Automation Test Execution Trend",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time as \"time\",\n  failed as Failed,\n  passed as Passed\nFROM\n  automation_execution_results\nWHERE suite_name='TC User Registration'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Result Last Test",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time as \"time\",\n  failed as Failed,\n  passed as Passed\nFROM\n  automation_execution_results\n"
    }
   ]
  }
 ]
}