version: '3.9'
services:
  robot-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./my_test:/app/my_test
      - ./reports:/app/reports
    environment:
      - FILENAME=test.robot
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.it
      PGADMIN_DEFAULT_PASSWORD: robot
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: robot
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    
volumes:
  postgresql_data:
  pgadmin_data:
  grafana_data:

